### ISSUE TITLE
Documentation is out-of-date

### ISSUE THREAD

**Issue by volks73** [clux/loggerv#11]
The documentation at http://clux.github.io/loggerv appears to be out-of-date/sync with v0.6. The old `*_color` methods are listed.

Is there a specific or automated procedure for generating the documentation with `rustdoc`?

**Comment by clux** [comment]
Oh, whoops. Yeah, thought I pushed docs.

I usually follow this: https://github.com/clux/dotfiles/blob/ad3bf1f5419f5763f314e65b8e66f622a9e4e988/.functions#L410-L416 which uses the `ghp-import` pip module. I think you'll have access to basically follow those steps now that you are a collaborator. Feel free to try.

**Comment by volks73** [comment]
Okay, I followed the function you provided to update the docs. It did not quite work for me without some modification. I had to use the HTTP address for the repository and the `ghp-import` did not appear to work, so I had to manually push the docs to the gh-pages. I have not used the `ghp-import` module before, so it could be me. Regardless, I was able to update the documentation.

**Comment by clux** [comment]
Ah, yeah. If you're cloning with http rather than ssh, that would cause that. Thanks for updating it :-)
