### ISSUE TITLE
Publish v0.7.1

### ISSUE THREAD

**Issue by volks73** [clux/loggerv#15]
While we are still working on #14, would it be possible to publish a new release, v0.7.1? 

The [ansi_term](https://crates.io/crates/ansi_term) crate recently published an update that fixes a problem with compiling/linking with the i686-pc-windows-msvc toolchain. I would like to propagate this fix to some of my Windows projects that are using this crate.

I have already bumped the dependency versions and Cargo.toml version, but I do not want to publish an update without @clux knowing about it or reviewing, just in case.

**Comment by clux** [comment]
Hey, yeah sure. Thanks.

I'll cargo publish :-)

**Comment by clux** [comment]
Done :-)
