### ISSUE TITLE
Documentation stills mention log::LogLevel instead of log::Level

### ISSUE THREAD

**Issue by XavierT** [clux/loggerv#21]
Hello, 

This is a really minor issue.

It is probably something that changed when log crate was updated to 0.4, but the documentation still mentions **loggerv::init_with_level(LogLevel::Info).unwrap()** which should now be **loggerv::init_with_level(Level::Info).unwrap()**

**Comment by clux** [comment]
Thanks! Will try to sort that in the next update!

(Although feel free to submit a PR).

**Comment by clux** [comment]
Oh, I misunderstood you. This was just github-pages D:

Have updated it now. Thanks for the reminder!
