### ISSUE TITLE
defaults_are_correct is failing on Fedora

### ISSUE THREAD

**Issue by igor-raits** [clux/loggerv#22]
```
---- tests::defaults_are_correct stdout ----
thread 'tests::defaults_are_correct' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', src/lib.rs:879:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
failures:
    tests::defaults_are_correct
```

Using latest Rust compiler. Let me know what additional info you would like to know.

**Comment by clux** [comment]
Thanks for the report! I think that's just you running the test on a non-tty. Regardless, have fixed master to account for the extra check. That test was definitely assuming too much.
